/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddCityForm: typeof import('./src/components/forms/AddCityForm.vue')['default']
    AddEmployeerForm: typeof import('./src/components/forms/AddEmployeerForm.vue')['default']
    AddShopForm: typeof import('./src/components/forms/AddShopForm.vue')['default']
    BaseDialog: typeof import('./src/components/BaseDialog.vue')['default']
    BaseForm: typeof import('./src/components/BaseForm.vue')['default']
    BaseModal: typeof import('./src/components/BaseModal.vue')['default']
    copy: typeof import('./src/components/forms/EditCityForm copy.vue')['default']
    CreatorMap: typeof import('./src/components/CreatorMap.vue')['default']
    EditCityForm: typeof import('./src/components/forms/EditCityForm.vue')['default']
    EditCityForm2: typeof import('./src/components/forms/EditCityForm2.vue')['default']
    EditCityForm3: typeof import('./src/components/forms/EditCityForm3.vue')['default']
    EditEmployeerForm: typeof import('./src/components/forms/EditEmployeerForm.vue')['default']
    EditRegionForm: typeof import('./src/components/forms/EditRegionForm.vue')['default']
    MapWrapper: typeof import('./src/components/MapWrapper.vue')['default']
    MyDialog: typeof import('./src/components/MyDialog.vue')['default']
    MyDialogII: typeof import('./src/components/MyDialogII.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tooltip: typeof import('./src/components/Tooltip.vue')['default']
  }
}
