/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddCityForm: typeof import('./src/components/forms/AddCityForm.vue')['default']
    AddEmployeerForm: typeof import('./src/components/forms/AddEmployeerForm.vue')['default']
    AddShopForm: typeof import('./src/components/forms/AddShopForm.vue')['default']
    CreatorMap: typeof import('./src/components/CreatorMap.vue')['default']
    EditCityForm: typeof import('./src/components/forms/EditCityForm.vue')['default']
    EditEmployeerForm: typeof import('./src/components/forms/EditEmployeerForm.vue')['default']
    EditRegionForm: typeof import('./src/components/forms/EditRegionForm.vue')['default']
    MapWrapper: typeof import('./src/components/MapWrapper.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
    Tooltip: typeof import('./src/components/Tooltip.vue')['default']
  }
}
